Models/BooksLoan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryApp1.Models
{
    public class BooksLoan
    {
        public int ID { get; set; }
        public DateTime IssuedData { get; set; }
        public DateTime ReturnedDate { get; set; }

        public int BooksId { get; set; }
        public int UsersId { get; set; }

        public Books Books { get; set; }
        public Users Users { get; set; }
    }
}

ViewModels/BooksLoanViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using LibraryApp1.Models;

namespace LibraryApp1.ViewModels
{
    public class BooksLoanViewModel
    {
     
        public Books Books { get; set; }

        
        public Users Users { get; set; }

        public BooksLoan BooksLoan{get;set;}
    }
}

Controllers/BooksLoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibraryApp1.Models;
using LibraryApp1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LibraryApp1.Controllers
{
    public class BooksLoanController : Controller
    {
        private readonly LibraryApp1Context _context;
        public BooksLoanController(LibraryApp1Context context)
        {
            _context = context;

        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = _context.BooksLoan.Include(b => b.Users).Include(a => a.Books).ThenInclude( au => au.Authors);
            return View(model.ToList());
        }

        public IActionResult AddBookLoan()
        {
            //books selected
            List<Books> books =new List<Books>();
            books = (from book in _context.Books
                    select book).Include(a => a.Authors).ToList();
            books.Insert(0, new Books{ ID = 0, bookTitle = "Select" });

            ViewBag.BooksList = books;


            //users selected
            List < Users > users = new List<Users>();
            users = (from user in _context.Users
                     select user).ToList();
            users.Insert(0, new Users { ID = 0, userName = "Select"});
            ViewBag.UsersList = users;


            return View();
        }

        [HttpPost]
        public IActionResult AddBookLoan(BooksLoan model)
        {

            if (ModelState.IsValid)
            {
                model.UsersId = model.UsersId;
                model.BooksId = model.BooksId;

                _context.BooksLoan.Add(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();           
          
        }
    }
}

Views/BooksLoan/AddBookLoan.cshtml
@model LibraryApp1.Models.BooksLoan

<h2>Loan Book</h2>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <form asp-action="AddBookLoan">
            <div class="form-group">
                <label class="control-label">Books</label>
                <select asp-for="BooksId" class="form-control" id="booksloaned" asp-items="@(new SelectList(ViewBag.BooksList,"ID","bookTitle"))"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Users</label>
                <select asp-for="UsersId" class="form-control" id="userss"
                        asp-items="@(new SelectList(ViewBag.UsersList,"ID","userName"))"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Loan book" />
            </div>
        </form>
    </div>

</div>

<script>
    $(function () {
        $('#booksloaned').on('change', function () {
            var value = $(this).children("option:selected").val();
            console.log(value);
        });

        $('#userss').on('change', function () {
            var valueuser = $(this).children("option:selected").val();
            console.log(valueuser);
        });
    });
</script>

Views/BooksLoan/Index.cshtml
@model IEnumerable<LibraryApp1.Models.BooksLoan>

<h1>Books Loaned</h1>
<div>
    <h3><a asp-controller="BooksLoan" asp-action="AddBookLoan">Loan Book</a></h3>
</div>
<table class="table textStyle">
    <thead>
        <tr>
            <th></th>
            <th>Book Title</th>
            <th>Author</th>
            <th>Borrowed date</th>
            <th>Returned date</th>
            <th>User</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr style="font-display:block">
            <td><div class="booksimage1"><img src="@item.Books.image"/></div></td>
            <td style="padding-top:50px">@item.Books.bookTitle</td>
            <td style="padding-top:50px">@item.Books.Authors.authorName</td>
            <td style="padding-top:50px">@item.IssuedData</td>
            <td style="padding-top:50px">@item.ReturnedDate</td>
            <td style="padding-top:50px">@item.Users.userName @item.Users.userSurname</td>
        </tr>
        }
    </tbody>
</table>